name : Mixin-Event-Dispatch

on:
  schedule:
    - cron: 42 3 * * 1

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install module
        run: curl -L https://cpanmin.us | perl - --configure-timeout=1920 Mixin::Event::Dispatch
