name : Tickit-Widget-Calendars

on:
  schedule:
    - cron: 42 3 * * 1

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: apt-get update
        run: sudo apt-get update
      - name: Install non alienazed dependencies
        run: sudo apt-get install libtool-bin pkg-config
      - name: Install module
        run: curl -L https://cpanmin.us | perl - --configure-timeout=1920 Tickit::Widget::Calendars
